FROM golang:1.13.12 AS build

WORKDIR /go/src/github.com/noname8753/vault-plugin-auth-google

ADD go.mod go.sum ./

RUN go mod download

ADD . ./

RUN CGO_ENABLED=0 go build -a -tags netgo -ldflags '-w' -o vault-plugin-auth-google
